name = input("Nombre: ")
apellido = input("Apellido: ")
rut = input("Rut: ")
correo = input("Duoc mail: ")
sede = input("Duoc sede: ")
print(f"Nombre: {name}") 
print(f"Apellido: {apellido}")
print(f"Rut: {rut}")
print(f"Duoc mail: {correo}")
print(f"Duoc sede: {sede}")
